spring.application.name=notification-service

server.port=8082

nats.url=${NATS_URL:nats://localhost:4222}

notification.max-deliver=5
# --- Email (Gmail SMTP) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# --- Database ---
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/notification_service_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
