spring.application.name=notification-service

server.port=8082

nats.url=${NATS_URL:nats://localhost:4222}

notification.max-deliver=5
# --- Email (Gmail SMTP) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true