spring.application.name=user-service

# --- Database ---
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/user_service_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# --- Server ---
server.port=8081

# --- JWT ---
jwt.secret=${JWT_SECRET:change-this-to-a-long-random-base64-secret-at-least-32-bytes-please}
jwt.expiration-ms=86400000
nats.url=${NATS_URL:nats://localhost:4222}